version: '3.8'

services:
  api:
    build: ./
    volumes:
      - '.:/usr/src/app'
      - node_modules:/usr/src/app/node_modules
    ports:
      - '8000:8000'

  db:
    image: mongo

volumes:
  node_modules:
